apiVersion: apps/v1
kind: Deployment
metadata:
  name: giropops-senhas-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: giropops-senhas
spec:
  replicas: 4
  selector:
    matchLabels:
      app: giropops-senhas
  template:
    metadata:
      labels:
        app: giropops-senhas
    spec:
      containers:
      - name: giropops-senhas
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 5000
        env:
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: giropops-senhas-env
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: giropops-senhas-env
              key: REDIS_PORT
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
