apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-giropops-senhas
  namespace: {{ .Values.namespace.name | default "default-namespace" }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: giropops-senhas-service
            port:
              number: 5000
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: {{ .Values.tls.secretName }}
