# apiVersion: v1
# kind: Service
# metadata:
#   name: redis-service
# spec:
#   selector:
#     app: redis
#   ports:
#     - protocol: TCP
#       port: 6379
#       targetPort: 6379
#   type: ClusterIP

apiVersion: v1
kind: Service
metadata:
  name: {{ include "giropops.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "giropops.labels" . | nindent 4 }}
    environment: {{ .Values.environmentLabel }}
spec:
  selector:
    app: {{ include "giropops.name" . }}
    environment: {{ .Values.environmentLabel }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
      targetPort: {{ .Values.service.port }}
      name: tcp-app
  type: {{ .Values.service.type }}
