apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: giropops-senhas-cert
  namespace: giropops-senhas
spec:
  secretName: {{ .Values.tls.secretName }}
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
  commonName: {{ .Values.ingress.host }}
  dnsNames:
  - {{ .Values.ingress.host }}
