apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "giropops-senhas.fullname" . }}
  labels:
    app: {{ include "giropops-senhas.name" . }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: [ {{ .Values.ingress.className }} ]
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: {{ .Values.ingress.path }}
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ include "giropops-senhas.fullname" . }}
            port:
              number: {{ .Values.service.port }}
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: {{ .Values.ingress.secretName }}

