deployments:
  - name: giropops-senhas
    namespace: giropops-senhas
    replicas: 5
    labels:
      app: giropops-senhas
      environment: prod
    containers:
      - image: willbossle/giropops-senhas:2.0
        name: giropops-senhas
        ports:
          - containerPort: 5000
        resources:
          limits:
            cpu: '0.5'
            memory: 384Mi
          requests:
            cpu: '0.1'
            memory: 128Mi
        imagePullPolicy: IfNotPresent
        env:
        - name: REDIS_HOST
          valueFrom:
              configMapKeyRef:
                name: giropops-senhas-env
                key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
              configMapKeyRef:
                name: giropops-senhas-env
                key: REDIS_PORT
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 3
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 3
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
    imagePullSecrets:
      - name: docker-hub-willber

  - name: deployment-redis
    namespace: giropops
    replicas: 1
    labels:
      app: redis
    containers:
      - name: redis
        image: willbossle/redis:2.0
        ports:
          - containerPort: 6379
        resources:
          limits:
            memory: "384Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "250m"
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
            add:
              - NET_BIND_SERVICE
              - CHOWN
              - SETUID
              - SETGID
        livenessProbe:
          tcpSocket:
            port: 6379
          timeoutSeconds: 5
          periodSeconds: 5
          failureThreshold: 5
          successThreshold: 1
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          timeoutSeconds: 5
          periodSeconds: 3
        command: ["redis-server", "--appendonly", "no"]
    imagePullSecrets:
      - name: docker-hub-willber
     
services:
  - name: giropops-senhas
    namespace: giropops-senhas
    selector:
      app: giropops-senhas
    ports:
      - protocol: TCP
        port: 5000
        targetPort: 5000

  - name: redis-service
    namespace: giropops-senhas
    selector:
      app: redis
    ports:
      - protocol: TCP
        port: 6379
        targetPort: 6379