FROM cgr.dev/chainguard/python:latest-dev AS buildando

WORKDIR /app
COPY /home/willber/Downloads/giropops-senhas/ /app/

RUN python -m venv /app/giropops-senhas
RUN apt install pip && /app/giropops-senhas/bin/pip install --user --no-cache-dir -r requirements.txt 
RUN /app/girpops-senhas/bin/pip install --upgrade flask

FROM cgr.dev/chainguard/python:latest

WORKDIR /app
COPY --from=buildando /home/nonroot/.local/lib/python3.12/site-packages /home/nonroot/.local/lib/python3.12/site-packages
#COPY . /app/

ENV REDIS_HOST=localhost

ENV PATH="/app/giropops-senhas/bin:$PATH"

COPY app.py .
COPY templates templates/
COPY static static/

EXPOSE 5000

ENTRYPOINT ["flask", "run", "--host=0.0.0.0"]


