env: prod  # ou outro valor padrão

deployments:
  - name: giropops-senhas-deployment
    namespace: giropops-senhas
    replicas: 5
    serviceAccountName: giropops-senhas-sa
    labels:
      app: giropops-senhas
    containers:
      - name: giropops-senhas
        image: willbossle/giropops-senhas:2.0
        ports:
          - containerPort: 5000
        env:
          - name: REDIS_HOST
            valueFrom:
              configMapKeyRef:
                name: giropops-senhas-env
                key: REDIS_HOST
          - name: REDIS_PORT
            valueFrom:
              configMapKeyRef:
                name: giropops-senhas-env
                key: REDIS_PORT
        resources:
          limits:
            cpu: '0.5'
            memory: 384Mi
          requests:
            cpu: '0.1'
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          capabilities:
            add: ["SYS_RESOURCE"]
            drop:
              - ALL
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 3
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 3
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
    imagePullSecrets:
      - name: docker-hub-willber
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 2
        maxUnavailable: 1

  - name: redis-deployment
    namespace: giropops-senhas
    replicas: 1
    serviceAccountName: redis-sa
    labels:
      app: redis
    containers:
      - name: redis
        image: willbossle/redis:2.0
        ports:
          - containerPort: 6379
        resources:
          limits:
            cpu: "0.3"
            memory: 128Mi
          requests:
            cpu: "0.1"
            memory: 128Mi
        securityContext:
          runAsUser: 1000
          runAsGroup: 3000
          allowPrivilegeEscalation: false
          capabilities:
            add: ["SYS_RESOURCE"]
            drop:
              - ALL
            add:
              - NET_BIND_SERVICE
              - CHOWN
              - SETUID
              - SETGID
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 5
          failureThreshold: 5
          successThreshold: 1
        readinessProbe:
          exec:
            command:
              - redis-cli
              - ping
          initialDelaySeconds: 20
          timeoutSeconds: 5
          periodSeconds: 3
        command: ["redis-server", "--appendonly", "no"]
    imagePullSecrets:
      - name: docker-hub-willber

services:
  - name: giropops-senhas-service
    namespace: giropops-senhas
    selector:
      app: giropops-senhas
    ports:
      - protocol: TCP
        port: 5000
        targetPort: 5000
        name: tcp-app

  - name: redis-service
    namespace: giropops-senhas
    selector:
      app: redis
    ports:
      - protocol: TCP
        port: 6379
        targetPort: 6379

service:
  type: ClusterIP  # Adicionado aqui para o template NOTES.txt
  port: 5000

# values.yaml
configMap:
  name: giropops-senhas-env
  namespace: giropops-senhas
  data:
    REDIS_HOST: "redis-service"
    REDIS_PORT: "6379"

hpa:
  name: hpa-giropops-senhas
  namespace: giropops-senhas
  minReplicas: 3
  maxReplicas: 10
  cpuUtilization: 50
  memoryUtilization: 50
  scaleUp:
    stabilizationWindowSeconds: 5
    percentPolicyValue: 90
    periodSeconds: 10
  scaleDown:
    stabilizationWindowSeconds: 60
    percentPolicyValue: 90
    periodSeconds: 10
  deploymentName: giropops-senhas

ingress:
  name: giropops-senhas-ingress
  namespace: giropops-senhas
  className: nginx
  host: giropops-senhas.local.com
  serviceName: giropops-senhas-service
  servicePort: 5000
  tlsSecretName: giropops-senhas-tls
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"

serviceAccounts:
  - name: giropops-senhas-sa
    namespace: giropops-senhas

  - name: redis-sa
    namespace: giropops-senhas
