apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: giropops-senhas
  name: giropops-senhas-deployment
  namespace: giropops-senhas
spec:
  replicas: 5
  selector:
    matchLabels:
      app: giropops-senhas
  template:
    metadata:
      labels:
        app: giropops-senhas
    spec:
      imagePullSecrets:
      - name: docker-hub-willber
      containers:
      - image: willbossle/giropops-senhas:2.0
        name: giropops-senhas
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: '0.5'
            memory: 384Mi
          requests:
            cpu: '0.1'
            memory: 128Mi
        imagePullPolicy: IfNotPresent
        env:
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: giropops-senhas-env
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: giropops-senhas-env
              key: REDIS_PORT
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          capabilities:
            add: ["SYS_RESOURCE"]
            drop:
            - ALL
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 3
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 3
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        volumeMounts:
        - name: tls-volume
          mountPath: /etc/tls
          readOnly: true
      volumes:
      - name: tls-volume
        secret:
          secretName: giropops-senhas-tls
          #certificado-giropops-senhas
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
