apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: senhas
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
  labels:
    app: giropops-senhas
  namespace: giropops-senhas

spec:
  ingressClassName: nginx
  rules:
  - host: giropops-senhas.willber.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: giropops-service
            port:
              number: 5000
  tls:
  - hosts:
    - giropops-senhas.local
    secretName: giropops-senhas-as-secret
